server:
  port: 8889

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

notification:
  from-email: Fova885@gmail.com
  
kafka:
  topic:
    user-events: user.events
    
logging:
  level:
    root: INFO
    com.notificationservice: DEBUG
    org.springframework.kafka: DEBUG
